AWSTemplateFormatVersion: '2010-09-09'
Description: Create a basic EBS volume

Resources:
  MyEBSVolume:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: us-east-1a   # Replace with your AZ
      Size: 8                        # Size in GiB
      VolumeType: gp2                # General Purpose SSD
      Tags:
        - Key: Name
          Value: MyFirstEBS

Outputs:
  VolumeId:
    Description: The ID of the EBS volume
    Value: !Ref MyEBSVolume
