name: Deploy Node.js App to EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2.pem
        chmod 600 ~/.ssh/ec2.pem
        cat >>~/.ssh/config <<END
        Host ec2
          HostName ${{ secrets.EC2_HOST }}
          User ${{ secrets.EC2_USERNAME }}
          IdentityFile ~/.ssh/ec2.pem
          StrictHostKeyChecking no
        END

    - name: Copy files to EC2
      run: |
        scp -r app/* ec2:/tmp/app/

    - name: Deploy to EC2
      run: |
        ssh ec2 '
          # Create app directory if it doesn't exist
          sudo mkdir -p /home/ubuntu/app
          
          # Copy files to app directory
          sudo cp -r /tmp/app/* /home/ubuntu/app/
          
          # Set proper permissions
          sudo chown -R ubuntu:ubuntu /home/ubuntu/app
          
          # Install dependencies
          cd /home/ubuntu/app
          npm install --production
          
          # Copy service file
          sudo cp /tmp/app/node-app.service /etc/systemd/system/
          
          # Reload systemd
          sudo systemctl daemon-reload
          
          # Enable and restart service
          sudo systemctl enable node-app
          sudo systemctl restart node-app
          
          # Check service status
          sudo systemctl status node-app
        ' 